#!/bin/bash

if [ $# -lt 1 ]; then
    echo "Использование: $0 расширение [каталог]"
    exit 1
fi

ext="$1"
dir="${2:-.}"

find "$dir" -maxdepth 1 -type f -name "*.$ext" -print0 | tar -cvf "files_$ext.tar" --null -T -
