#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Использование: $0 \"текст\""
    exit 1
fi

text="$1"
len=${#text}
line="+$(printf '%*s' $((len + 2)) '' | tr ' ' '-')+"

echo "$line"
echo "| $text |"
echo "$line"
